---
- hosts: all
  become: yes
  tasks:
    - name: Download Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Python requests
      package:
        name: python3-requests
        state: present

    - name: Create a network with custom IPAM config
      docker_network:
        name: Mario_network
        ipam_config:
          - subnet: 192.168.10.0/24
            gateway: 192.168.10.1


