Vagrant.configure("2") do |config|
  config.vm.hostname = "Franco"
  config.vm.box = "rockylinux/9"
  config.vm.network "private_network", ip: "192.168.10.101"
  config.vbguest.auto_update = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end 
end
